version: "3.9"
services:
  python_shell:
    build:
      context: .
    container_name: python_shell
    image: python_shell:latest
    ports:
      - "4353:4353"
    security_opt:
      - no-new-privileges:true
    environment:
      - PORT=4353
      - TIMEOUT=2
      - UPLOAD_LIMIT=4096
#    read_only: true
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 512M
        reservations:
          memory: 64M
      restart_policy:
        condition: on-failure
        max_attempts: 5
